name: Build SEQR docker image
on: workflow_dispatch

jobs:
  deploy_server:
    runs-on: ubuntu-latest

    env:
      AZURE_CR: msseqr01acr.azurecr.io

    steps:
    - name: "checkout seqr repo"
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        recursive: 'true'

    - name: 'Set up image name variables'
      run: |
        # Set up container registry authentication for image push.
        echo "CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')" >> $GITHUB_ENV
        echo "CLIENT_PWD=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')" >> $GITHUB_ENV

        # Set up image name and tag.
        BUILDTAG=$(TZ=America/Los_Angeles date +'%y%m%d-%H%M%S')
        echo "Build/push ${AZURE_CR}/seqr:${BUILDTAG}"
        echo "SEQR_IMAGE=${AZURE_CR}/seqr" >> $GITHUB_ENV
        echo "IMAGE_TAG=${BUILDTAG}" >> $GITHUB_ENV

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CR }}
        username: ${{ env.CLIENT_ID }}
        password: ${{ env.CLIENT_PWD }}
    - run: |
        docker build \
          --tag ${SEQR_IMAGE}:${IMAGE_TAG} \
          --tag ${SEQR_IMAGE}:latest \
          -f seqr/deploy/docker/seqr/Dockerfile seqr
        docker push ${SEQR_IMAGE}:${IMAGE_TAG}
        docker push ${SEQR_IMAGE}:latest
